// prisma/seed.ts
import { PrismaClient, JobOrigin, JobStatus, LocationType, EmploymentType } from "@prisma/client";

const prisma = new PrismaClient();

const SAMPLE_COMPANIES = [
  {
    name: "Northwind Security",
    slug: "northwind-security",
    websiteUrl: "https://northwindsecurity.example",
    domain: "northwindsecurity.com",
    logoUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&auto=format&fit=crop&q=80",
    description: "Northwind Security builds automated autonomous detection and threat mitigation platforms for high-growth SaaS enterprises.",
  },
  {
    name: "Acme Cloud",
    slug: "acme-cloud",
    websiteUrl: "https://acmecloud.example",
    domain: "acmecloud.example",
    logoUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80",
    description: "Global cloud security and infrastructure defense provider powering Fortune 500 resilient Kubernetes clusters.",
  },
  {
    name: "Contoso Defense",
    slug: "contoso-defense",
    websiteUrl: "https://contosodefense.example",
    domain: "contosodefense.example",
    logoUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=128&auto=format&fit=crop&q=80",
    description: "Specialized defense contractor and red-team penetration testing consultancy safeguarding critical cloud networks.",
  },
  {
    name: "Sentinel Cyber",
    slug: "sentinel-cyber",
    websiteUrl: "https://sentinelcyber.example",
    domain: "sentinelcyber.example",
    logoUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80",
    description: "Managed Detection & Response (MDR) provider delivering 24/7 SIEM monitoring and live threat neutralization.",
  },
  {
    name: "ShieldScale Labs",
    slug: "shieldscale-labs",
    websiteUrl: "https://shieldscale.example",
    domain: "shieldscale.example",
    logoUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=128&auto=format&fit=crop&q=80",
    description: "Zero-trust architecture and automated GRC platform helping modern fintechs achieve instant SOC2 and ISO compliance.",
  },
];

const SAMPLE_JOBS = [
  // 1
  {
    title: "SOC Analyst (L2 Remote)",
    slug: "soc-analyst-l2-northwind-k9x1",
    companyIndex: 0,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "SOC / Detection",
    seniority: "Mid",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "IN", "PH", "PL"],
    salaryMin: 55000,
    salaryMax: 85000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: true,
    applyUrl: "https://northwindsecurity.example/careers/soc-analyst-l2",
    descriptionHtml: `<h3>Role Overview</h3><p>Join Northwind's 24/7 Global SOC protecting cloud enterprise customers against sophisticated adversaries.</p><h4>Key Responsibilities:</h4><ul><li>Triage alerts from EDR (CrowdStrike/SentinelOne) and cloud SIEM (Splunk/Datadog)</li><li>Perform initial containment and escalate priority incidents</li><li>Author detection rules using Sigma and KQL</li></ul>`,
  },
  // 2
  {
    title: "Senior Detection Engineer",
    slug: "senior-detection-engineer-acme-c3m2",
    companyIndex: 1,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "SOC / Detection",
    seniority: "Senior",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "US", "CA", "EU"],
    salaryMin: 140000,
    salaryMax: 175000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: true,
    applyUrl: "https://acmecloud.example/jobs/sr-detection-eng",
    descriptionHtml: `<h3>About The Position</h3><p>Acme Cloud is seeking an experienced Detection Engineer to build proactive behavioral detections across multi-tenant AWS and Kubernetes environments.</p><h4>Requirements:</h4><ul><li>5+ years experience in threat detection engineering</li><li>Fluent in Python/Go and automation workflows</li><li>Deep knowledge of MITRE ATT&CK framework</li></ul>`,
  },
  // 3
  {
    title: "Lead Application Security Engineer",
    slug: "lead-appsec-engineer-shieldscale-p8r4",
    companyIndex: 4,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "AppSec",
    seniority: "Lead",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "US", "EU"],
    salaryMin: 165000,
    salaryMax: 210000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: true,
    applyUrl: "https://shieldscale.example/jobs/lead-appsec",
    descriptionHtml: `<h3>Lead Our Product Security</h3><p>Embed security into modern CI/CD pipelines, conduct threat modeling for microservices, and oversee bug bounty programs.</p><ul><li>Lead SAST/DAST integrations</li><li>Perform architectural threat reviews with engineering leads</li><li>Mentor software engineers in secure coding best practices</li></ul>`,
  },
  // 4
  {
    title: "Cloud Security Architect",
    slug: "cloud-security-architect-contoso-j7w1",
    companyIndex: 2,
    origin: JobOrigin.ATS,
    status: JobStatus.LIVE,
    category: "Cloud Security",
    seniority: "Lead",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["US", "EU"],
    salaryMin: 170000,
    salaryMax: 220000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://contosodefense.example/apply/cloud-sec-arch",
    descriptionHtml: `<h3>Design Cloud Resilience</h3><p>Architect resilient zero-trust foundations across AWS, GCP, and Azure for defense clients.</p>`,
  },
  // 5
  {
    title: "Product Security Engineer (DevSecOps)",
    slug: "prodsec-devsecops-northwind-v4l8",
    companyIndex: 0,
    origin: JobOrigin.ATS,
    status: JobStatus.LIVE,
    category: "AppSec",
    seniority: "Mid",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE"],
    salaryMin: 120000,
    salaryMax: 155000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://northwindsecurity.example/careers/prodsec-engineer",
    descriptionHtml: `<h3>Build Secure Software Delivery</h3><p>Implement automated security scanning into GitHub Actions pipelines and triage vulnerability reports.</p>`,
  },
  // 6
  {
    title: "Incident Response Specialist",
    slug: "incident-response-specialist-sentinel-t2q9",
    companyIndex: 3,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "SOC / Detection",
    seniority: "Senior",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "EU", "APAC"],
    salaryMin: 130000,
    salaryMax: 165000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://sentinelcyber.example/careers/ir-specialist",
    descriptionHtml: `<h3>Lead Digital Forensics and Incident Handling</h3><p>Be the tip of the spear in investigating and neutralizing active intrusions for enterprise clients globally.</p>`,
  },
  // 7
  {
    title: "GRC & Security Compliance Manager",
    slug: "grc-compliance-manager-shieldscale-k1z5",
    companyIndex: 4,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "GRC / Compliance",
    seniority: "Senior",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["US", "CA"],
    salaryMin: 135000,
    salaryMax: 160000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://shieldscale.example/careers/grc-manager",
    descriptionHtml: `<h3>Lead Enterprise Audits</h3><p>Manage SOC 2 Type II, ISO 27001, and HIPAA compliance programs while keeping security agile and developer-friendly.</p>`,
  },
  // 8
  {
    title: "Offensive Security / Penetration Tester",
    slug: "penetration-tester-contoso-m9a3",
    companyIndex: 2,
    origin: JobOrigin.ATS,
    status: JobStatus.LIVE,
    category: "Security Engineering",
    seniority: "Senior",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE"],
    salaryMin: 125000,
    salaryMax: 160000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://contosodefense.example/jobs/pentester",
    descriptionHtml: `<h3>Red Team Operations</h3><p>Execute simulated adversary attacks against web applications, cloud networks, and external perimeter surfaces.</p>`,
  },
  // 9
  {
    title: "Cyber Threat Intelligence Analyst",
    slug: "cti-analyst-sentinel-w3x7",
    companyIndex: 3,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "Threat Intelligence",
    seniority: "Mid",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "US", "EU"],
    salaryMin: 95000,
    salaryMax: 130000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://sentinelcyber.example/jobs/cti-analyst",
    descriptionHtml: `<h3>Track Advanced Threat Actors</h3><p>Monitor dark web forums, analyze indicator feeds, and publish strategic threat advisories for customers.</p>`,
  },
  // 10
  {
    title: "IAM Solutions Architect",
    slug: "iam-solutions-architect-acme-d8v2",
    companyIndex: 1,
    origin: JobOrigin.ATS,
    status: JobStatus.LIVE,
    category: "Security Engineering",
    seniority: "Senior",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "US", "CA"],
    salaryMin: 150000,
    salaryMax: 185000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://acmecloud.example/careers/iam-architect",
    descriptionHtml: `<h3>Zero-Trust Identity</h3><p>Architect Okta, Entra ID, and PAM solutions for automated privilege lifecycle governance across 10,000+ identities.</p>`,
  },
  // 11
  {
    title: "Junior SOC Analyst",
    slug: "junior-soc-analyst-northwind-y1k4",
    companyIndex: 0,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "SOC / Detection",
    seniority: "Junior",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "IN", "PH"],
    salaryMin: 40000,
    salaryMax: 60000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://northwindsecurity.example/careers/junior-soc",
    descriptionHtml: `<h3>Kickstart Your Cybersecurity Career</h3><p>Great entry-level opportunity for aspiring analysts with foundational networking and Linux security skills.</p>`,
  },
  // 12
  {
    title: "Kubernetes Security Engineer",
    slug: "k8s-security-engineer-acme-r7t6",
    companyIndex: 1,
    origin: JobOrigin.ATS,
    status: JobStatus.LIVE,
    category: "Cloud Security",
    seniority: "Senior",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "US", "EU"],
    salaryMin: 145000,
    salaryMax: 180000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://acmecloud.example/careers/k8s-sec-engineer",
    descriptionHtml: `<h3>Container Defense</h3><p>Harden container runtimes using Cilium, Falco, and Kyverno policies at scale.</p>`,
  },
  // 13
  {
    title: "AppSec Vulnerability Researcher",
    slug: "appsec-vulnerability-researcher-contoso-h5j8",
    companyIndex: 2,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "AppSec",
    seniority: "Senior",
    employmentType: EmploymentType.CONTRACT,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE"],
    salaryMin: 80,
    salaryMax: 120,
    salaryCurrency: "USD",
    salaryPeriod: "HOUR",
    isFeatured: false,
    applyUrl: "https://contosodefense.example/jobs/vuln-researcher",
    descriptionHtml: `<h3>0-Day and Deep Code Auditing</h3><p>Perform deep source code audits in C/Rust/Go and discover high-severity logic flaws.</p>`,
  },
  // 14
  {
    title: "Security Risk & Audit Analyst",
    slug: "security-risk-analyst-shieldscale-b9m1",
    companyIndex: 4,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "GRC / Compliance",
    seniority: "Mid",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "EU", "UK"],
    salaryMin: 80000,
    salaryMax: 105000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://shieldscale.example/careers/risk-analyst",
    descriptionHtml: `<h3>Vendor Risk & Compliance Assessments</h3><p>Assess third-party SaaS vendors, maintain risk registers, and support customer security reviews.</p>`,
  },
  // 15
  {
    title: "SIEM & SOAR Automation Engineer",
    slug: "siem-soar-engineer-sentinel-e3p5",
    companyIndex: 3,
    origin: JobOrigin.ATS,
    status: JobStatus.LIVE,
    category: "SOC / Detection",
    seniority: "Mid",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE"],
    salaryMin: 110000,
    salaryMax: 140000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://sentinelcyber.example/jobs/soar-engineer",
    descriptionHtml: `<h3>Automate Incident Playbooks</h3><p>Develop Tines and Cortex XSOAR playbooks to automatically triage phishing and credential stuffing attacks.</p>`,
  },
  // 16
  {
    title: "Principal Security Architect",
    slug: "principal-security-architect-acme-x9n2",
    companyIndex: 1,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "Security Engineering",
    seniority: "Principal",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "US", "CA"],
    salaryMin: 210000,
    salaryMax: 265000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://acmecloud.example/careers/principal-architect",
    descriptionHtml: `<h3>Shape Enterprise Security Strategy</h3><p>Provide executive technical leadership for cybersecurity posture across all product lines.</p>`,
  },
  // 17
  {
    title: "Reverse Engineer & Malware Analyst",
    slug: "malware-reverse-engineer-contoso-k4v7",
    companyIndex: 2,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "Threat Intelligence",
    seniority: "Senior",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE"],
    salaryMin: 140000,
    salaryMax: 175000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://contosodefense.example/jobs/malware-analyst",
    descriptionHtml: `<h3>Deconstruct Advanced Payloads</h3><p>Reverse engineer compiled Windows and Linux binaries using Ghidra and IDA Pro to extract C2 indicators.</p>`,
  },
  // 18
  {
    title: "AWS Cloud Security Specialist",
    slug: "aws-cloud-security-specialist-northwind-a8b3",
    companyIndex: 0,
    origin: JobOrigin.ATS,
    status: JobStatus.LIVE,
    category: "Cloud Security",
    seniority: "Mid",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "US", "LATAM"],
    salaryMin: 125000,
    salaryMax: 150000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://northwindsecurity.example/jobs/aws-security",
    descriptionHtml: `<h3>Multi-Account AWS Governance</h3><p>Implement AWS Organizations SCPs, GuardDuty findings automation, and IAM Identity Center policies.</p>`,
  },
  // 19
  {
    title: "Product Security Consultant",
    slug: "product-security-consultant-shieldscale-g2c6",
    companyIndex: 4,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "AppSec",
    seniority: "Mid",
    employmentType: EmploymentType.CONTRACT,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE"],
    salaryMin: 75,
    salaryMax: 100,
    salaryCurrency: "USD",
    salaryPeriod: "HOUR",
    isFeatured: false,
    applyUrl: "https://shieldscale.example/apply/prodsec-consultant",
    descriptionHtml: `<h3>Threat Modeling for Startups</h3><p>Help high-growth startups model threats and secure their GraphQL and REST API endpoints.</p>`,
  },
  // 20
  {
    title: "Lead Threat Hunter",
    slug: "lead-threat-hunter-sentinel-z6r1",
    companyIndex: 3,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "SOC / Detection",
    seniority: "Lead",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "US", "EU"],
    salaryMin: 155000,
    salaryMax: 190000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://sentinelcyber.example/careers/threat-hunter",
    descriptionHtml: `<h3>Hypothesis-Driven Threat Hunting</h3><p>Formulate and execute hunts across large-scale telemetry data to discover undetected malicious persistence.</p>`,
  },
  // 21
  {
    title: "Privacy & Data Protection Engineer",
    slug: "privacy-data-protection-shieldscale-q3m8",
    companyIndex: 4,
    origin: JobOrigin.ATS,
    status: JobStatus.LIVE,
    category: "GRC / Compliance",
    seniority: "Senior",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["EU", "UK", "US"],
    salaryMin: 140000,
    salaryMax: 170000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://shieldscale.example/jobs/privacy-engineer",
    descriptionHtml: `<h3>GDPR & Data Privacy Engineering</h3><p>Architect automated data retention, encryption at rest, and differential privacy mechanisms.</p>`,
  },
  // 22
  {
    title: "Zero Trust Network Engineer",
    slug: "zero-trust-network-engineer-acme-w5k7",
    companyIndex: 1,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "Security Engineering",
    seniority: "Senior",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "US", "EU"],
    salaryMin: 145000,
    salaryMax: 180000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://acmecloud.example/careers/zero-trust",
    descriptionHtml: `<h3>Software-Defined Perimeter</h3><p>Deploy WireGuard, Cloudflare Access, and mTLS mesh across distributed multi-region clouds.</p>`,
  },
  // 23
  {
    title: "Cybersecurity Intern",
    slug: "cybersecurity-intern-northwind-c1v9",
    companyIndex: 0,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "SOC / Detection",
    seniority: "Junior",
    employmentType: EmploymentType.INTERNSHIP,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "US", "IN"],
    salaryMin: 3000,
    salaryMax: 4500,
    salaryCurrency: "USD",
    salaryPeriod: "MONTH",
    isFeatured: false,
    applyUrl: "https://northwindsecurity.example/careers/internship",
    descriptionHtml: `<h3>Paid Summer & Fall Cyber Internship</h3><p>Mentored program working with senior security architects on vulnerability management and script automation.</p>`,
  },
  // 24
  {
    title: "Dark Web Intelligence Specialist",
    slug: "dark-web-intel-specialist-sentinel-j8n3",
    companyIndex: 3,
    origin: JobOrigin.ATS,
    status: JobStatus.LIVE,
    category: "Threat Intelligence",
    seniority: "Mid",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE"],
    salaryMin: 95000,
    salaryMax: 125000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://sentinelcyber.example/jobs/darkweb-intel",
    descriptionHtml: `<h3>Adversary Infiltration Research</h3><p>Track illicit breaches, credential dumps, and ransomware leak sites to provide early warning indicators.</p>`,
  },
  // 25
  {
    title: "CI/CD Pipeline Security Specialist",
    slug: "pipeline-security-specialist-shieldscale-k9d2",
    companyIndex: 4,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "AppSec",
    seniority: "Senior",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "US", "CA"],
    salaryMin: 135000,
    salaryMax: 165000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://shieldscale.example/jobs/pipeline-security",
    descriptionHtml: `<h3>Software Supply Chain Defense</h3><p>Secure SLSA provenance, Cosign container signing, and artifact provenance across GitHub workflows.</p>`,
  },
  // 26
  {
    title: "Senior Azure Cloud Security Architect",
    slug: "senior-azure-sec-architect-contoso-x2m4",
    companyIndex: 2,
    origin: JobOrigin.ATS,
    status: JobStatus.LIVE,
    category: "Cloud Security",
    seniority: "Senior",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["US", "EU"],
    salaryMin: 160000,
    salaryMax: 195000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://contosodefense.example/jobs/azure-architect",
    descriptionHtml: `<h3>Enterprise Azure Architecture</h3><p>Architect Microsoft Defender for Cloud, Sentinel SIEM, and Entra Private Access for sovereign cloud workloads.</p>`,
  },
  // 27
  {
    title: "SOC Shift Lead (Weekend Coverage)",
    slug: "soc-shift-lead-weekend-northwind-p4b7",
    companyIndex: 0,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "SOC / Detection",
    seniority: "Lead",
    employmentType: EmploymentType.PART_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE"],
    salaryMin: 60,
    salaryMax: 85,
    salaryCurrency: "USD",
    salaryPeriod: "HOUR",
    isFeatured: false,
    applyUrl: "https://northwindsecurity.example/careers/weekend-lead",
    descriptionHtml: `<h3>Weekend Incident Commander</h3><p>Lead the weekend response queue and coordinate communication with customer C-suite stakeholders during critical escalations.</p>`,
  },
  // 28
  {
    title: "Threat Modeling Specialist",
    slug: "threat-modeling-specialist-acme-f7h1",
    companyIndex: 1,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "AppSec",
    seniority: "Senior",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "EU", "APAC"],
    salaryMin: 130000,
    salaryMax: 165000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://acmecloud.example/careers/threat-modeling",
    descriptionHtml: `<h3>STRIDE Threat Modeling</h3><p>Facilitate structured threat modeling sessions for high-throughput distributed microservices.</p>`,
  },
  // 29
  {
    title: "Head of Information Security (vCISO)",
    slug: "head-of-information-security-contoso-l1q8",
    companyIndex: 2,
    origin: JobOrigin.DIRECT,
    status: JobStatus.LIVE,
    category: "GRC / Compliance",
    seniority: "Director",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["US", "EU"],
    salaryMin: 220000,
    salaryMax: 290000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://contosodefense.example/jobs/vciso",
    descriptionHtml: `<h3>Executive Security Direction</h3><p>Define enterprise security strategy, report to the board of directors, and guide total risk governance.</p>`,
  },
  // 30
  {
    title: "Cryptography & Key Management Engineer",
    slug: "cryptography-key-management-shieldscale-v3z9",
    companyIndex: 4,
    origin: JobOrigin.ATS,
    status: JobStatus.LIVE,
    category: "Security Engineering",
    seniority: "Senior",
    employmentType: EmploymentType.FULL_TIME,
    locationType: LocationType.REMOTE,
    eligibleRegions: ["WORLDWIDE", "US", "EU"],
    salaryMin: 155000,
    salaryMax: 195000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    isFeatured: false,
    applyUrl: "https://shieldscale.example/jobs/crypto-engineer",
    descriptionHtml: `<h3>Post-Quantum & Enterprise HSM</h3><p>Implement HashiCorp Vault, AWS KMS multi-region key rotation, and post-quantum cryptographic primitives.</p>`,
  },
];

export async function main() {
  console.log("🌱 Starting seed for NicheJobs...");

  // Upsert Companies
  const createdCompanies = [];
  for (const comp of SAMPLE_COMPANIES) {
    const record = await prisma.company.upsert({
      where: { slug: comp.slug },
      update: {
        name: comp.name,
        websiteUrl: comp.websiteUrl,
        domain: comp.domain,
        logoUrl: comp.logoUrl,
        description: comp.description,
      },
      create: comp,
    });
    createdCompanies.push(record);
    console.log(`  🏢 Company: ${record.name}`);
  }

  // Create ATS Sources for Appendix A companies
  const atsSources = [
    {
      companyId: createdCompanies[0].id,
      provider: "GREENHOUSE" as const,
      boardToken: "northwindsecurity",
    },
    {
      companyId: createdCompanies[1].id,
      provider: "ASHBY" as const,
      boardToken: "acmecloud",
    },
    {
      companyId: createdCompanies[2].id,
      provider: "LEVER" as const,
      boardToken: "contosodefense",
    },
  ];

  for (const src of atsSources) {
    await prisma.atsSource.upsert({
      where: {
        provider_boardToken: {
          provider: src.provider,
          boardToken: src.boardToken,
        },
      },
      update: {
        companyId: src.companyId,
      },
      create: {
        companyId: src.companyId,
        provider: src.provider,
        boardToken: src.boardToken,
        active: true,
      },
    });
  }

  // Upsert 30 Jobs
  const now = new Date();
  const thirtyDaysAhead = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000);

  for (let i = 0; i < SAMPLE_JOBS.length; i++) {
    const item = SAMPLE_JOBS[i];
    const company = createdCompanies[item.companyIndex];

    const job = await prisma.job.upsert({
      where: { slug: item.slug },
      update: {
        title: item.title,
        status: item.status,
        category: item.category,
        seniority: item.seniority,
        employmentType: item.employmentType,
        locationType: item.locationType,
        eligibleRegions: item.eligibleRegions,
        salaryMin: item.salaryMin,
        salaryMax: item.salaryMax,
        salaryCurrency: item.salaryCurrency,
        salaryPeriod: item.salaryPeriod,
        isFeatured: item.isFeatured,
        applyUrl: item.applyUrl,
        descriptionHtml: item.descriptionHtml,
      },
      create: {
        slug: item.slug,
        title: item.title,
        origin: item.origin,
        status: item.status,
        companyId: company.id,
        category: item.category,
        seniority: item.seniority,
        employmentType: item.employmentType,
        locationType: item.locationType,
        eligibleRegions: item.eligibleRegions,
        salaryMin: item.salaryMin,
        salaryMax: item.salaryMax,
        salaryCurrency: item.salaryCurrency,
        salaryPeriod: item.salaryPeriod,
        isFeatured: item.isFeatured,
        applyUrl: item.applyUrl,
        descriptionHtml: item.descriptionHtml,
        publishedAt: new Date(now.getTime() - i * 12 * 60 * 60 * 1000), // staggered published dates
        expiresAt: thirtyDaysAhead,
      },
    });

    console.log(`  💼 Job [${i + 1}/30]: ${job.title} (${company.name})`);
  }

  // Seed sample affiliate offer (Section 15 & M7 preview)
  await prisma.affiliateOffer.upsert({
    where: { id: "seed-cert-offer-1" },
    update: {},
    create: {
      id: "seed-cert-offer-1",
      name: "CompTIA Security+ & CISSP Exam Vouchers",
      url: "https://partner.example.com/certs?ref=nichejobs",
      category: "CERTIFICATION",
      headline: "Preparing for cybersecurity certifications?",
      body: "Get 20% off verified practice tests and official exam vouchers with code NICHE20.",
      placements: ["JOB_PAGE", "ALERT_EMAIL", "NEWSLETTER"],
      active: true,
    },
  });

  console.log("✅ Seed completed successfully! 5 companies, 30 jobs, ATS sources & affiliate offers ready.");
}

if (require.main === module) {
  main()
    .catch((e) => {
      console.error("❌ Seed error:", e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
